/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./resources/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-dim": "#d6dade",
        "tertiary-fixed-dim": "#4cd7f6",
        "on-secondary-fixed-variant": "#38485d",
        "tertiary": "#000000",
        "on-primary-fixed-variant": "#173bab",
        "outline-variant": "#c6c6cd",
        "primary-container": "#001453",
        "surface-bright": "#f6fafe",
        "secondary-fixed-dim": "#b7c8e1",
        "on-primary-fixed": "#001453",
        "on-primary": "#ffffff",
        "surface-container-highest": "#dfe3e7",
        "primary-fixed": "#dde1ff",
        "surface-tint": "#3755c3",
        "surface-container-low": "#f0f4f8",
        "on-tertiary-fixed-variant": "#004e5c",
        "surface-container": "#eaeef2",
        "secondary-container": "#d0e1fb",
        "background": "#f6fafe",
        "on-secondary-fixed": "#0b1c30",
        "on-surface": "#171c1f",
        "secondary-fixed": "#d3e4fe",
        "on-error": "#ffffff",
        "outline": "#76777d",
        "on-background": "#171c1f",
        "surface": "#f6fafe",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#001f26",
        "inverse-surface": "#2c3134",
        "inverse-on-surface": "#edf1f5",
        "primary-fixed-dim": "#b8c4ff",
        "secondary": "#505f76",
        "on-tertiary-container": "#0090a9",
        "on-primary-container": "#607cec",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#acedff",
        "surface-variant": "#dfe3e7",
        "primary": "#000000",
        "tertiary-container": "#001f26",
        "on-surface-variant": "#45464d",
        "inverse-primary": "#b8c4ff",
        "error": "#ba1a1a",
        "on-secondary-container": "#54647a",
        "surface-container-high": "#e4e9ed"
      },
      fontFamily: {
        headline: ["Manrope"],
        body: ["Inter"],
        label: ["Inter"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
}